-- 1 -> LISTANDO CLIENTES DO BANCO:
SELECT * FROM PESSOA;

-- 2 -> LISTANDO CLIENTES ORGANIZADOS POR CIDADE E ORDEM ALFABÉTICA:
SELECT CIDADE, NOME_COMPLETO
FROM PESSOA
ORDER BY CIDADE, NOME_COMPLETO;
