-- CRIANDO PROCEDURE BÁSICA:
DELIMITER $$ 

CREATE PROCEDURE OBTER_SALDO(IN ID_DA_CONTA_PASSADA INT)
BEGIN
	-- DECLARANDO VARIÁVEL LOCAL:
    DECLARE SALDO_DA_CONTA DECIMAL(10,2);
    DECLARE VALOR_DE_MOVIMENTACOES DECIMAL(10,2);
    DECLARE SALDO_ATUAL DECIMAL(10,2);
   
	-- OBTENDO O VALOR DE MOVIMENTACOES QUE O OBJETO FEZ:
    SELECT SUM(VALOR_DO_MOVIMENTO) INTO VALOR_DE_MOVIMENTACOES 
    FROM MOVIMENTO_CONTA 
    WHERE ID_DA_CONTA = ID_DA_CONTA_PASSADA;
    
	-- OBTENDO O SALDO INICIAL DO OBJETO:
	SELECT SALDO INTO SALDO_DA_CONTA
    FROM CONTA
    WHERE ID_DA_CONTA = ID_DA_CONTA_PASSADA;
    
	-- ATRIBUINDO AO VALOR DE SALDO A DIFERENCA ENTRE O VALOR E AS MOVIMENTAÇÕES:
	SET SALDO_ATUAL = SALDO_DA_CONTA - VALOR_DE_MOVIMENTACOES;

	-- EXIBINDO VALOR QUE FOI ATRIBUIDO À VARIÁVEL:
	SELECT SALDO_ATUAL AS SALDO_APOS_MOVIMENTACOES;
END
$$

-- PROCEDURA QUE ATUALIZA O VALOR DO SALDO DE UMA CONTA DE ACORDO COM O VALOR DAS MOVIMENTACOES QUE ELE FEZ:
DELIMITER $$
CREATE PROCEDURE ATUALIZAR_SALDO(IN CODIGO_CONTA INT)
BEGIN
	-- VARIÁVEL QUE RECEBERÁ P VALOR DO SALDO ATUALIZADO:
	DECLARE SALDO_ATUALIZADO DECIMAL(10,2);
			
	-- ATRIBUINDO O VALOR DAS MOVIMENTAÇÕES DE DETERMINADA CONTA PARA A VARIÁVEL:
	SET SALDO_ATUALIZADO = (SELECT SUM(VALOR_DO_MOVIMENTO) 
    FROM MOVIMENTO_CONTA WHERE ID_DA_CONTA = CODIGO_CONTA );
            
    /* ATUALIZANDO O VALOR DO SALDO DA CONTA DE ACORDO COM O VALOR DO RESULTADO DAS MOVIMENTAÇÕES        
	QUE FORAM FEITAS: */
	UPDATE CONTA
    SET SALDO = SALDO_ATUALIZADO
    WHERE ID_DA_CONTA = CODIGO_CONTA;
    
    -- EXIBINDO VALORES APÓS A ATUALIZAÇÃO:
	SELECT P.NOME_COMPLETO AS NOME, C.SALDO AS SALDO_ATUAL
    FROM PESSOA P, CONTA C
    WHERE P.ID_PESSOA = C.PESSOA_VINCULADA AND C.ID_DA_CONTA = CODIGO_CONTA;  
    
END
	
$$

/* PROCEDURE QUE INSERE UMA INSTÂNCIA 'PESSOA' NA TABELA E VERIFICA SE ESSE VALOR JÁ EXISTE. SE ESSE 
VALOR NÃO EXISTIR, ELE CADASTRA UMA CONTA PARA A NOVA PESSOA CADASTRADA: */

DELIMITER $$
CREATE PROCEDURE INSERIR_PESSOA(PRIMEIRO_NOME VARCHAR(40), SOBRENOME VARCHAR(40), DATA_DE_NASCIMENTO DATE,
CIDADE VARCHAR(40), ESTADO CHAR(2))
BEGIN
	-- VARIÁVEL QUE ARMAZENA O NOME COMPLETO INSERIDO:
    DECLARE NOME_COMPLETO_INSERIDO VARCHAR(100); 
    
    -- DECLARAÇÃO DE VARIÁVEL QUE REALIZA A CONTAGEM DE VALORES DE 'NOME COMPLETO' IGUAIS NA TABELA:
	DECLARE CONTAGEM_DE_NOMES_IGUAIS INT;
    
    /* DECLARANDO VARIÁVEL QUE ARMAZENA O VALOR DO ID DA NOVA PESSOA QUE FOI INSERIDA PARA QUANDO FOR
    FEITA A CRIAÇÃO DA CONTA RELACIONADA: */
    DECLARE ID_DA_NOVA_PESSOA INT;
    
    -- OBTENDO O NOME COMPLETO:
    SET NOME_COMPLETO_INSERIDO = CONCAT(PRIMEIRO_NOME, ' ', SOBRENOME);
	
	-- VERIFICANDO SE HÁ VALORES IGUAIS:
    SELECT COUNT(*) INTO CONTAGEM_DE_NOMES_IGUAIS
    FROM PESSOA
    WHERE NOME_COMPLETO = NOME_COMPLETO_INSERIDO;
    
    -- SE AINDA NÃO EXISTE, É FEITA A INSERÇÃO:
    IF CONTAGEM_DE_NOMES_IGUAIS > 0 THEN
        SELECT 'O NOME INSERIDO JÁ EXISTE NA TABELA.' AS MENSAGEM_DE_ERRO;
    ELSE
		-- INSERINDO:
        INSERT INTO PESSOA(PRIMEIRO_NOME, SOBRENOME, DATA_DE_NASCIMENTO, CIDADE, ESTADO)
        VALUES 
        (PRIMEIRO_NOME, SOBRENOME, DATA_DE_NASCIMENTO, CIDADE, ESTADO);
        -- APÓS INSERIR,CADASTRA DOIS VALORES DE 'CONTA' PARA A PESSOA:
        SET ID_DA_NOVA_PESSOA = (SELECT ID_PESSOA FROM PESSOA WHERE NOME_COMPLETO = NOME_COMPLETO_INSERIDO);
        INSERT INTO CONTA(PESSOA_VINCULADA, TIPO_DE_CONTA, NUMERO_DE_CONTA, SALDO)
        VALUES
        (ID_DA_NOVA_PESSOA, 'CC', 1048, 1000),
        (ID_DA_NOVA_PESSOA, 'CP', 2048, 2890);
        
        SELECT 'OBJETO INSERIDO COM SUSCESSO!' AS MENSAGEM;
    END IF;

END
$$




